### ISSUE TITLE
마이페이지 UI

### ISSUE THREAD

**Issue by ldh-dodo** [MobileProgrammingJBNU/Local-Events-Sharing-App#4]
## Description
기능 구현 전, 마이페이지 UI 구성
## To-do
- [x]  신뢰온도 ProgressBar 구성
- [x]  내가 작성한 글, 댓글, 즐겨찾기, 로그아웃 항목 추가.
- [x] 닉네임 및 프로필 수정
- [x] 프로필 수정과, 실제 프로필 수정 액티비티와 연결 및 이동 전환
